# Site settings
# accessible in the templates via {{ site.myvariable }}.
title: Ben Gillbanks - Internet Nobody
description: ""

baseurl: "" # the subpath of your site, e.g. /blog
url: https://bengillbanks.co.uk
twitter_username: binarymoon
github_username: binarymoon
github: [metadata]
repository: BinaryMoon/BenGillbanks
permalink: /blog/:year/:title/
google_analytics: UA-55722-11
logo: /assets/images/favicon-192.png


# Collections
collections:
- projects
- timeline
- social

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - _pages
